// Bring-your-own-key provider registry — curated fallback model lists only.
// Live catalogs come from fetchByokModels; these shortlists keep the dropdown
// usable offline or when a provider is momentarily unreachable.
import { env } from "../config";
import type { ByokProvider, ByokProviderId } from "../byokTypes";

export const BYOK_PROVIDERS: Record<ByokProviderId, ByokProvider> = {
  openrouter: {
    id: "openrouter",
    name: "OpenRouter",
    kind: "openai",
    baseUrl: env.OPENROUTER_BASE_URL,
    keyPattern: /^sk-or-[A-Za-z0-9_-]{20,}$/,
    keyHint: "sk-or-...",
    keylessModels: true,
    streamUsage: true,
    models: [
      "openai/gpt-4o-mini",
      "openai/gpt-4o",
      "google/gemini-2.5-flash",
      "anthropic/claude-sonnet-4.5",
      "meta-llama/llama-3.3-70b-instruct",
      "deepseek/deepseek-r1",
    ],
    chatHeaders: { "HTTP-Referer": env.APP_ORIGIN, "X-Title": "ChatUI" },
  },
  openai: {
    id: "openai",
    name: "OpenAI",
    kind: "openai",
    baseUrl: "https://api.openai.com/v1",
    keyPattern: /^sk-[A-Za-z0-9_-]{20,}$/,
    keyHint: "sk-...",
    keylessModels: false,
    streamUsage: true,
    models: ["gpt-4.1", "gpt-4.1-mini", "gpt-4.1-nano", "gpt-4o", "gpt-4o-mini", "o4-mini", "o3-mini"],
  },
  google: {
    id: "google",
    name: "Google Gemini",
    kind: "gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta",
    keyPattern: /^(AIza[A-Za-z0-9_-]{20,}|[A-Za-z0-9][A-Za-z0-9_.-]{24,})$/,
    keyHint: "AIza... or AQ....",
    keylessModels: false,
    models: ["gemini-2.5-flash", "gemini-2.5-pro", "gemini-2.0-flash", "gemini-2.0-flash-lite"],
  },
  grok: {
    id: "grok",
    name: "Grok (xAI)",
    kind: "openai",
    baseUrl: "https://api.x.ai/v1",
    keyPattern: /^xai-[A-Za-z0-9_-]{20,}$/,
    keyHint: "xai-...",
    keylessModels: false,
    models: ["grok-4", "grok-3", "grok-3-fast", "grok-3-mini", "grok-2-1212"],
  },
  meta: {
    id: "meta",
    name: "Meta Llama",
    kind: "openai",
    baseUrl: "https://api.llama.com/compat/v1",
    keyPattern: /^(LLM\|[A-Za-z0-9_|.-]{8,}|[A-Za-z0-9_-]{20,})$/,
    keyHint: "LLM|...",
    keylessModels: false,
    models: [
      "Llama-4-Maverick-17B-128E-Instruct-FP8",
      "Llama-4-Scout-17B-16E-Instruct-FP8",
      "Llama-3.3-70B-Instruct",
      "Llama-3.3-8B-Instruct",
    ],
  },
  nvidia: {
    id: "nvidia",
    name: "NVIDIA NIM",
    kind: "openai",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    keyPattern: /^nvapi-[A-Za-z0-9_-]{20,}$/,
    keyHint: "nvapi-...",
    keylessModels: true,
    allModelsFree: true,
    models: [
      "meta/llama-3.3-70b-instruct",
      "nvidia/llama-3.1-nemotron-70b-instruct",
      "deepseek-ai/deepseek-r1",
      "mistralai/mistral-large-2-instruct",
      "qwen/qwen3-235b-a22b",
    ],
  },
  deepseek: {
    id: "deepseek",
    name: "DeepSeek",
    kind: "openai",
    baseUrl: "https://api.deepseek.com",
    keyPattern: /^sk-[A-Za-z0-9]{20,}$/,
    keyHint: "sk-...",
    keylessModels: false,
    models: ["deepseek-chat", "deepseek-reasoner"],
  },
  qwen: {
    id: "qwen",
    name: "Qwen (Alibaba)",
    kind: "openai",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    keyPattern: /^sk-[A-Za-z0-9]{20,}$/,
    keyHint: "sk-...",
    keylessModels: false,
    models: ["qwen-max", "qwen-plus", "qwen-turbo", "qwen3-235b-a22b", "qwen3-30b-a3b"],
  },
  moonshot: {
    id: "moonshot",
    name: "Moonshot (Kimi)",
    kind: "openai",
    baseUrl: "https://api.moonshot.ai/v1",
    keyPattern: /^sk-[A-Za-z0-9]{20,}$/,
    keyHint: "sk-...",
    keylessModels: false,
    models: ["kimi-k2-0711-preview", "kimi-latest", "moonshot-v1-8k", "moonshot-v1-32k", "moonshot-v1-128k"],
  },
  groq: {
    id: "groq",
    name: "Groq",
    kind: "openai",
    baseUrl: "https://api.groq.com/openai/v1",
    keyPattern: /^gsk_[A-Za-z0-9]{20,}$/,
    keyHint: "gsk_...",
    keylessModels: false,
    allModelsFree: true,
    models: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "qwen-qwq-32b", "deepseek-r1-distill-llama-70b"],
  },
  mistral: {
    id: "mistral",
    name: "Mistral AI",
    kind: "openai",
    baseUrl: "https://api.mistral.ai/v1",
    keyPattern: /^[A-Za-z0-9]{30,}$/,
    keyHint: "30+ character token",
    keylessModels: false,
    models: ["mistral-large-latest", "mistral-medium-latest", "mistral-small-latest", "codestral-latest"],
  },
  anthropic: {
    id: "anthropic",
    name: "Anthropic (Claude)",
    kind: "anthropic",
    baseUrl: "https://api.anthropic.com/v1",
    keyPattern: /^sk-ant-[A-Za-z0-9_-]{20,}$/,
    keyHint: "sk-ant-...",
    keylessModels: false,
    models: ["claude-sonnet-4-5", "claude-opus-4-1", "claude-haiku-4-5"],
  },
  cleanapis: {
    id: "cleanapis",
    name: "CleanAPIs",
    kind: "openai",
    baseUrl: "https://cleanapis.com/v1",
    keyPattern: /^cc_[A-Za-z0-9_-]{16,}$/,
    keyHint: "cc_...",
    keylessModels: false,
    // Fallback shortlist (live /v1/models wins when reachable): public ids
    // from the CleanAPIs catalog. Keeps the dropdown usable offline or when
    // the key lacks the models:read scope.
    models: [
      "claude-opus-4.8",
      "gpt-5.6-luna",
      "deepseek-v4-flash-0731",
      "deepseek-v4-pro-0813",
      "qwen3.8-27b",
      "seed-2.1-turbo",
      "gemma-2-2b",
    ],
  },
  infron: {
    id: "infron",
    name: "Infron",
    kind: "openai",
    baseUrl: "https://llm.onerouter.pro/v1",
    keyPattern: /^[A-Za-z0-9][A-Za-z0-9_.-]{15,}$/,
    keyHint: "your API key",
    keylessModels: true,
    // Fallback shortlist (live /v1/models is keyless and wins when
    // reachable): ids observed on the live catalog.
    models: [
      "openai/gpt-6-luna",
      "openai/gpt-6-sol",
      "google/gemini-3.1-flash-lite",
      "inclusionai/ling-2.6-1t",
      "interfaze/interfaze-beta",
    ],
  },
  apinex: {
    id: "apinex",
    name: "APInex",
    kind: "openai",
    baseUrl: "https://apinex.bond/v1",
    keyPattern: /^[A-Za-z0-9][A-Za-z0-9_.-]{15,}$/,
    keyHint: "your API key",
    keylessModels: false,
    models: [],
  },
  codecraft: {
    id: "codecraft",
    name: "CodeCraft API",
    kind: "openai",
    baseUrl: "https://codecraftapi.com/v1",
    keyPattern: /^cc_[A-Za-z0-9_-]{16,}$/,
    keyHint: "cc_...",
    keylessModels: false,
    models: ["gpt-5.6-luna", "deepseek-v4-flash-0731", "qwen3.8-27b", "gemini-3.7-flash", "kimi-k2.6", "grok-4.5"],
  },
};

export const getByokProvider = (raw: unknown): ByokProvider | null => {
  if (typeof raw !== "string") return null;
  return BYOK_PROVIDERS[raw.trim().toLowerCase() as ByokProviderId] ?? null;
};
